### ISSUE TITLE
the .readme is still ben bot

### ISSUE THREAD

**Issue by sebastianwhiffen** [Baggiest/HawkTuah#1]
I am extremely passionate about this project and I wont stand for seeing such lazy development within the readme. as you probably know the readme is the most important part of any project. I am appalled.

**Comment by Baggiest** [comment]
Here u go 💖

**Comment by sebastianwhiffen** [comment]
> Here u go 💖

Thank you deeply. I'm not sure how much longer I could have lasted without this fix.
